export interface PageInfo {
  surah: number;
  ayah: number;
}

export const QURAN_PAGE_STARTS: PageInfo[] = [
  { surah: 1, ayah: 1 }, // Page undefined
  { surah: 2, ayah: 1 }, // Page undefined
  { surah: 2, ayah: 6 }, // Page undefined
  { surah: 2, ayah: 17 }, // Page undefined
  { surah: 2, ayah: 25 }, // Page undefined
  { surah: 2, ayah: 30 }, // Page undefined
  { surah: 2, ayah: 38 }, // Page undefined
  { surah: 2, ayah: 49 }, // Page undefined
  { surah: 2, ayah: 58 }, // Page undefined
  { surah: 2, ayah: 62 }, // Page undefined
  { surah: 2, ayah: 70 }, // Page undefined
  { surah: 2, ayah: 77 }, // Page undefined
  { surah: 2, ayah: 84 }, // Page undefined
  { surah: 2, ayah: 89 }, // Page undefined
  { surah: 2, ayah: 94 }, // Page undefined
  { surah: 2, ayah: 102 }, // Page undefined
  { surah: 2, ayah: 106 }, // Page undefined
  { surah: 2, ayah: 113 }, // Page undefined
  { surah: 2, ayah: 120 }, // Page undefined
  { surah: 2, ayah: 127 }, // Page undefined
  { surah: 2, ayah: 135 }, // Page undefined
  { surah: 2, ayah: 142 }, // Page undefined
  { surah: 2, ayah: 146 }, // Page undefined
  { surah: 2, ayah: 154 }, // Page undefined
  { surah: 2, ayah: 164 }, // Page undefined
  { surah: 2, ayah: 170 }, // Page undefined
  { surah: 2, ayah: 177 }, // Page undefined
  { surah: 2, ayah: 182 }, // Page undefined
  { surah: 2, ayah: 187 }, // Page undefined
  { surah: 2, ayah: 191 }, // Page undefined
  { surah: 2, ayah: 197 }, // Page undefined
  { surah: 2, ayah: 203 }, // Page undefined
  { surah: 2, ayah: 211 }, // Page undefined
  { surah: 2, ayah: 216 }, // Page undefined
  { surah: 2, ayah: 220 }, // Page undefined
  { surah: 2, ayah: 225 }, // Page undefined
  { surah: 2, ayah: 231 }, // Page undefined
  { surah: 2, ayah: 234 }, // Page undefined
  { surah: 2, ayah: 238 }, // Page undefined
  { surah: 2, ayah: 246 }, // Page undefined
  { surah: 2, ayah: 249 }, // Page undefined
  { surah: 2, ayah: 253 }, // Page undefined
  { surah: 2, ayah: 257 }, // Page undefined
  { surah: 2, ayah: 260 }, // Page undefined
  { surah: 2, ayah: 265 }, // Page undefined
  { surah: 2, ayah: 270 }, // Page undefined
  { surah: 2, ayah: 275 }, // Page undefined
  { surah: 2, ayah: 282 }, // Page undefined
  { surah: 2, ayah: 283 }, // Page undefined
  { surah: 3, ayah: 1 }, // Page undefined
  { surah: 3, ayah: 10 }, // Page undefined
  { surah: 3, ayah: 16 }, // Page undefined
  { surah: 3, ayah: 23 }, // Page undefined
  { surah: 3, ayah: 30 }, // Page undefined
  { surah: 3, ayah: 38 }, // Page undefined
  { surah: 3, ayah: 46 }, // Page undefined
  { surah: 3, ayah: 53 }, // Page undefined
  { surah: 3, ayah: 62 }, // Page undefined
  { surah: 3, ayah: 71 }, // Page undefined
  { surah: 3, ayah: 78 }, // Page undefined
  { surah: 3, ayah: 84 }, // Page undefined
  { surah: 3, ayah: 92 }, // Page undefined
  { surah: 3, ayah: 101 }, // Page undefined
  { surah: 3, ayah: 109 }, // Page undefined
  { surah: 3, ayah: 116 }, // Page undefined
  { surah: 3, ayah: 122 }, // Page undefined
  { surah: 3, ayah: 133 }, // Page undefined
  { surah: 3, ayah: 141 }, // Page undefined
  { surah: 3, ayah: 149 }, // Page undefined
  { surah: 3, ayah: 154 }, // Page undefined
  { surah: 3, ayah: 158 }, // Page undefined
  { surah: 3, ayah: 166 }, // Page undefined
  { surah: 3, ayah: 174 }, // Page undefined
  { surah: 3, ayah: 181 }, // Page undefined
  { surah: 3, ayah: 187 }, // Page undefined
  { surah: 3, ayah: 195 }, // Page undefined
  { surah: 4, ayah: 1 }, // Page undefined
  { surah: 4, ayah: 7 }, // Page undefined
  { surah: 4, ayah: 12 }, // Page undefined
  { surah: 4, ayah: 15 }, // Page undefined
  { surah: 4, ayah: 20 }, // Page undefined
  { surah: 4, ayah: 24 }, // Page undefined
  { surah: 4, ayah: 27 }, // Page undefined
  { surah: 4, ayah: 34 }, // Page undefined
  { surah: 4, ayah: 38 }, // Page undefined
  { surah: 4, ayah: 45 }, // Page undefined
  { surah: 4, ayah: 52 }, // Page undefined
  { surah: 4, ayah: 60 }, // Page undefined
  { surah: 4, ayah: 66 }, // Page undefined
  { surah: 4, ayah: 75 }, // Page undefined
  { surah: 4, ayah: 80 }, // Page undefined
  { surah: 4, ayah: 87 }, // Page undefined
  { surah: 4, ayah: 92 }, // Page undefined
  { surah: 4, ayah: 95 }, // Page undefined
  { surah: 4, ayah: 102 }, // Page undefined
  { surah: 4, ayah: 106 }, // Page undefined
  { surah: 4, ayah: 114 }, // Page undefined
  { surah: 4, ayah: 122 }, // Page undefined
  { surah: 4, ayah: 128 }, // Page undefined
  { surah: 4, ayah: 135 }, // Page undefined
  { surah: 4, ayah: 141 }, // Page undefined
  { surah: 4, ayah: 148 }, // Page undefined
  { surah: 4, ayah: 155 }, // Page undefined
  { surah: 4, ayah: 163 }, // Page undefined
  { surah: 4, ayah: 171 }, // Page undefined
  { surah: 4, ayah: 176 }, // Page undefined
  { surah: 5, ayah: 3 }, // Page undefined
  { surah: 5, ayah: 6 }, // Page undefined
  { surah: 5, ayah: 10 }, // Page undefined
  { surah: 5, ayah: 14 }, // Page undefined
  { surah: 5, ayah: 18 }, // Page undefined
  { surah: 5, ayah: 24 }, // Page undefined
  { surah: 5, ayah: 32 }, // Page undefined
  { surah: 5, ayah: 37 }, // Page undefined
  { surah: 5, ayah: 42 }, // Page undefined
  { surah: 5, ayah: 46 }, // Page undefined
  { surah: 5, ayah: 51 }, // Page undefined
  { surah: 5, ayah: 58 }, // Page undefined
  { surah: 5, ayah: 65 }, // Page undefined
  { surah: 5, ayah: 71 }, // Page undefined
  { surah: 5, ayah: 77 }, // Page undefined
  { surah: 5, ayah: 83 }, // Page undefined
  { surah: 5, ayah: 90 }, // Page undefined
  { surah: 5, ayah: 96 }, // Page undefined
  { surah: 5, ayah: 104 }, // Page undefined
  { surah: 5, ayah: 109 }, // Page undefined
  { surah: 5, ayah: 114 }, // Page undefined
  { surah: 6, ayah: 1 }, // Page undefined
  { surah: 6, ayah: 9 }, // Page undefined
  { surah: 6, ayah: 19 }, // Page undefined
  { surah: 6, ayah: 28 }, // Page undefined
  { surah: 6, ayah: 36 }, // Page undefined
  { surah: 6, ayah: 45 }, // Page undefined
  { surah: 6, ayah: 53 }, // Page undefined
  { surah: 6, ayah: 60 }, // Page undefined
  { surah: 6, ayah: 69 }, // Page undefined
  { surah: 6, ayah: 74 }, // Page undefined
  { surah: 6, ayah: 82 }, // Page undefined
  { surah: 6, ayah: 91 }, // Page undefined
  { surah: 6, ayah: 95 }, // Page undefined
  { surah: 6, ayah: 102 }, // Page undefined
  { surah: 6, ayah: 111 }, // Page undefined
  { surah: 6, ayah: 119 }, // Page undefined
  { surah: 6, ayah: 125 }, // Page undefined
  { surah: 6, ayah: 132 }, // Page undefined
  { surah: 6, ayah: 138 }, // Page undefined
  { surah: 6, ayah: 143 }, // Page undefined
  { surah: 6, ayah: 147 }, // Page undefined
  { surah: 6, ayah: 152 }, // Page undefined
  { surah: 6, ayah: 158 }, // Page undefined
  { surah: 7, ayah: 1 }, // Page undefined
  { surah: 7, ayah: 12 }, // Page undefined
  { surah: 7, ayah: 23 }, // Page undefined
  { surah: 7, ayah: 31 }, // Page undefined
  { surah: 7, ayah: 38 }, // Page undefined
  { surah: 7, ayah: 44 }, // Page undefined
  { surah: 7, ayah: 52 }, // Page undefined
  { surah: 7, ayah: 58 }, // Page undefined
  { surah: 7, ayah: 68 }, // Page undefined
  { surah: 7, ayah: 74 }, // Page undefined
  { surah: 7, ayah: 82 }, // Page undefined
  { surah: 7, ayah: 88 }, // Page undefined
  { surah: 7, ayah: 96 }, // Page undefined
  { surah: 7, ayah: 105 }, // Page undefined
  { surah: 7, ayah: 121 }, // Page undefined
  { surah: 7, ayah: 131 }, // Page undefined
  { surah: 7, ayah: 138 }, // Page undefined
  { surah: 7, ayah: 144 }, // Page undefined
  { surah: 7, ayah: 150 }, // Page undefined
  { surah: 7, ayah: 156 }, // Page undefined
  { surah: 7, ayah: 160 }, // Page undefined
  { surah: 7, ayah: 164 }, // Page undefined
  { surah: 7, ayah: 171 }, // Page undefined
  { surah: 7, ayah: 179 }, // Page undefined
  { surah: 7, ayah: 188 }, // Page undefined
  { surah: 7, ayah: 196 }, // Page undefined
  { surah: 8, ayah: 1 }, // Page undefined
  { surah: 8, ayah: 9 }, // Page undefined
  { surah: 8, ayah: 17 }, // Page undefined
  { surah: 8, ayah: 26 }, // Page undefined
  { surah: 8, ayah: 34 }, // Page undefined
  { surah: 8, ayah: 41 }, // Page undefined
  { surah: 8, ayah: 46 }, // Page undefined
  { surah: 8, ayah: 53 }, // Page undefined
  { surah: 8, ayah: 62 }, // Page undefined
  { surah: 8, ayah: 70 }, // Page undefined
  { surah: 9, ayah: 1 }, // Page undefined
  { surah: 9, ayah: 7 }, // Page undefined
  { surah: 9, ayah: 14 }, // Page undefined
  { surah: 9, ayah: 21 }, // Page undefined
  { surah: 9, ayah: 27 }, // Page undefined
  { surah: 9, ayah: 32 }, // Page undefined
  { surah: 9, ayah: 37 }, // Page undefined
  { surah: 9, ayah: 41 }, // Page undefined
  { surah: 9, ayah: 48 }, // Page undefined
  { surah: 9, ayah: 55 }, // Page undefined
  { surah: 9, ayah: 62 }, // Page undefined
  { surah: 9, ayah: 69 }, // Page undefined
  { surah: 9, ayah: 73 }, // Page undefined
  { surah: 9, ayah: 80 }, // Page undefined
  { surah: 9, ayah: 87 }, // Page undefined
  { surah: 9, ayah: 94 }, // Page undefined
  { surah: 9, ayah: 100 }, // Page undefined
  { surah: 9, ayah: 107 }, // Page undefined
  { surah: 9, ayah: 112 }, // Page undefined
  { surah: 9, ayah: 118 }, // Page undefined
  { surah: 9, ayah: 123 }, // Page undefined
  { surah: 10, ayah: 1 }, // Page undefined
  { surah: 10, ayah: 7 }, // Page undefined
  { surah: 10, ayah: 15 }, // Page undefined
  { surah: 10, ayah: 21 }, // Page undefined
  { surah: 10, ayah: 26 }, // Page undefined
  { surah: 10, ayah: 34 }, // Page undefined
  { surah: 10, ayah: 43 }, // Page undefined
  { surah: 10, ayah: 54 }, // Page undefined
  { surah: 10, ayah: 62 }, // Page undefined
  { surah: 10, ayah: 71 }, // Page undefined
  { surah: 10, ayah: 79 }, // Page undefined
  { surah: 10, ayah: 89 }, // Page undefined
  { surah: 10, ayah: 98 }, // Page undefined
  { surah: 10, ayah: 107 }, // Page undefined
  { surah: 11, ayah: 6 }, // Page undefined
  { surah: 11, ayah: 13 }, // Page undefined
  { surah: 11, ayah: 20 }, // Page undefined
  { surah: 11, ayah: 29 }, // Page undefined
  { surah: 11, ayah: 38 }, // Page undefined
  { surah: 11, ayah: 46 }, // Page undefined
  { surah: 11, ayah: 54 }, // Page undefined
  { surah: 11, ayah: 63 }, // Page undefined
  { surah: 11, ayah: 72 }, // Page undefined
  { surah: 11, ayah: 82 }, // Page undefined
  { surah: 11, ayah: 89 }, // Page undefined
  { surah: 11, ayah: 98 }, // Page undefined
  { surah: 11, ayah: 109 }, // Page undefined
  { surah: 11, ayah: 118 }, // Page undefined
  { surah: 12, ayah: 5 }, // Page undefined
  { surah: 12, ayah: 15 }, // Page undefined
  { surah: 12, ayah: 23 }, // Page undefined
  { surah: 12, ayah: 31 }, // Page undefined
  { surah: 12, ayah: 38 }, // Page undefined
  { surah: 12, ayah: 44 }, // Page undefined
  { surah: 12, ayah: 53 }, // Page undefined
  { surah: 12, ayah: 64 }, // Page undefined
  { surah: 12, ayah: 70 }, // Page undefined
  { surah: 12, ayah: 79 }, // Page undefined
  { surah: 12, ayah: 87 }, // Page undefined
  { surah: 12, ayah: 96 }, // Page undefined
  { surah: 12, ayah: 104 }, // Page undefined
  { surah: 13, ayah: 1 }, // Page undefined
  { surah: 13, ayah: 6 }, // Page undefined
  { surah: 13, ayah: 14 }, // Page undefined
  { surah: 13, ayah: 19 }, // Page undefined
  { surah: 13, ayah: 29 }, // Page undefined
  { surah: 13, ayah: 35 }, // Page undefined
  { surah: 13, ayah: 43 }, // Page undefined
  { surah: 14, ayah: 6 }, // Page undefined
  { surah: 14, ayah: 11 }, // Page undefined
  { surah: 14, ayah: 19 }, // Page undefined
  { surah: 14, ayah: 25 }, // Page undefined
  { surah: 14, ayah: 34 }, // Page undefined
  { surah: 14, ayah: 43 }, // Page undefined
  { surah: 15, ayah: 1 }, // Page undefined
  { surah: 15, ayah: 16 }, // Page undefined
  { surah: 15, ayah: 32 }, // Page undefined
  { surah: 15, ayah: 52 }, // Page undefined
  { surah: 15, ayah: 71 }, // Page undefined
  { surah: 15, ayah: 91 }, // Page undefined
  { surah: 16, ayah: 7 }, // Page undefined
  { surah: 16, ayah: 15 }, // Page undefined
  { surah: 16, ayah: 27 }, // Page undefined
  { surah: 16, ayah: 35 }, // Page undefined
  { surah: 16, ayah: 43 }, // Page undefined
  { surah: 16, ayah: 55 }, // Page undefined
  { surah: 16, ayah: 65 }, // Page undefined
  { surah: 16, ayah: 73 }, // Page undefined
  { surah: 16, ayah: 80 }, // Page undefined
  { surah: 16, ayah: 88 }, // Page undefined
  { surah: 16, ayah: 94 }, // Page undefined
  { surah: 16, ayah: 103 }, // Page undefined
  { surah: 16, ayah: 111 }, // Page undefined
  { surah: 16, ayah: 119 }, // Page undefined
  { surah: 17, ayah: 1 }, // Page undefined
  { surah: 17, ayah: 8 }, // Page undefined
  { surah: 17, ayah: 18 }, // Page undefined
  { surah: 17, ayah: 28 }, // Page undefined
  { surah: 17, ayah: 39 }, // Page undefined
  { surah: 17, ayah: 50 }, // Page undefined
  { surah: 17, ayah: 59 }, // Page undefined
  { surah: 17, ayah: 67 }, // Page undefined
  { surah: 17, ayah: 76 }, // Page undefined
  { surah: 17, ayah: 87 }, // Page undefined
  { surah: 17, ayah: 97 }, // Page undefined
  { surah: 17, ayah: 105 }, // Page undefined
  { surah: 18, ayah: 5 }, // Page undefined
  { surah: 18, ayah: 16 }, // Page undefined
  { surah: 18, ayah: 21 }, // Page undefined
  { surah: 18, ayah: 28 }, // Page undefined
  { surah: 18, ayah: 35 }, // Page undefined
  { surah: 18, ayah: 46 }, // Page undefined
  { surah: 18, ayah: 54 }, // Page undefined
  { surah: 18, ayah: 62 }, // Page undefined
  { surah: 18, ayah: 75 }, // Page undefined
  { surah: 18, ayah: 84 }, // Page undefined
  { surah: 18, ayah: 98 }, // Page undefined
  { surah: 19, ayah: 1 }, // Page undefined
  { surah: 19, ayah: 12 }, // Page undefined
  { surah: 19, ayah: 26 }, // Page undefined
  { surah: 19, ayah: 39 }, // Page undefined
  { surah: 19, ayah: 52 }, // Page undefined
  { surah: 19, ayah: 65 }, // Page undefined
  { surah: 19, ayah: 77 }, // Page undefined
  { surah: 19, ayah: 96 }, // Page undefined
  { surah: 20, ayah: 13 }, // Page undefined
  { surah: 20, ayah: 38 }, // Page undefined
  { surah: 20, ayah: 52 }, // Page undefined
  { surah: 20, ayah: 65 }, // Page undefined
  { surah: 20, ayah: 77 }, // Page undefined
  { surah: 20, ayah: 88 }, // Page undefined
  { surah: 20, ayah: 99 }, // Page undefined
  { surah: 20, ayah: 114 }, // Page undefined
  { surah: 20, ayah: 126 }, // Page undefined
  { surah: 21, ayah: 1 }, // Page undefined
  { surah: 21, ayah: 11 }, // Page undefined
  { surah: 21, ayah: 25 }, // Page undefined
  { surah: 21, ayah: 36 }, // Page undefined
  { surah: 21, ayah: 45 }, // Page undefined
  { surah: 21, ayah: 58 }, // Page undefined
  { surah: 21, ayah: 73 }, // Page undefined
  { surah: 21, ayah: 82 }, // Page undefined
  { surah: 21, ayah: 91 }, // Page undefined
  { surah: 21, ayah: 102 }, // Page undefined
  { surah: 22, ayah: 1 }, // Page undefined
  { surah: 22, ayah: 6 }, // Page undefined
  { surah: 22, ayah: 16 }, // Page undefined
  { surah: 22, ayah: 24 }, // Page undefined
  { surah: 22, ayah: 31 }, // Page undefined
  { surah: 22, ayah: 39 }, // Page undefined
  { surah: 22, ayah: 47 }, // Page undefined
  { surah: 22, ayah: 56 }, // Page undefined
  { surah: 22, ayah: 65 }, // Page undefined
  { surah: 22, ayah: 73 }, // Page undefined
  { surah: 23, ayah: 1 }, // Page undefined
  { surah: 23, ayah: 18 }, // Page undefined
  { surah: 23, ayah: 28 }, // Page undefined
  { surah: 23, ayah: 43 }, // Page undefined
  { surah: 23, ayah: 60 }, // Page undefined
  { surah: 23, ayah: 75 }, // Page undefined
  { surah: 23, ayah: 90 }, // Page undefined
  { surah: 23, ayah: 105 }, // Page undefined
  { surah: 24, ayah: 1 }, // Page undefined
  { surah: 24, ayah: 11 }, // Page undefined
  { surah: 24, ayah: 21 }, // Page undefined
  { surah: 24, ayah: 28 }, // Page undefined
  { surah: 24, ayah: 32 }, // Page undefined
  { surah: 24, ayah: 37 }, // Page undefined
  { surah: 24, ayah: 44 }, // Page undefined
  { surah: 24, ayah: 54 }, // Page undefined
  { surah: 24, ayah: 59 }, // Page undefined
  { surah: 24, ayah: 62 }, // Page undefined
  { surah: 25, ayah: 3 }, // Page undefined
  { surah: 25, ayah: 12 }, // Page undefined
  { surah: 25, ayah: 21 }, // Page undefined
  { surah: 25, ayah: 33 }, // Page undefined
  { surah: 25, ayah: 44 }, // Page undefined
  { surah: 25, ayah: 56 }, // Page undefined
  { surah: 25, ayah: 68 }, // Page undefined
  { surah: 26, ayah: 1 }, // Page undefined
  { surah: 26, ayah: 20 }, // Page undefined
  { surah: 26, ayah: 40 }, // Page undefined
  { surah: 26, ayah: 61 }, // Page undefined
  { surah: 26, ayah: 84 }, // Page undefined
  { surah: 26, ayah: 112 }, // Page undefined
  { surah: 26, ayah: 137 }, // Page undefined
  { surah: 26, ayah: 160 }, // Page undefined
  { surah: 26, ayah: 184 }, // Page undefined
  { surah: 26, ayah: 207 }, // Page undefined
  { surah: 27, ayah: 1 }, // Page undefined
  { surah: 27, ayah: 14 }, // Page undefined
  { surah: 27, ayah: 23 }, // Page undefined
  { surah: 27, ayah: 36 }, // Page undefined
  { surah: 27, ayah: 45 }, // Page undefined
  { surah: 27, ayah: 56 }, // Page undefined
  { surah: 27, ayah: 64 }, // Page undefined
  { surah: 27, ayah: 77 }, // Page undefined
  { surah: 27, ayah: 89 }, // Page undefined
  { surah: 28, ayah: 6 }, // Page undefined
  { surah: 28, ayah: 14 }, // Page undefined
  { surah: 28, ayah: 22 }, // Page undefined
  { surah: 28, ayah: 29 }, // Page undefined
  { surah: 28, ayah: 36 }, // Page undefined
  { surah: 28, ayah: 44 }, // Page undefined
  { surah: 28, ayah: 51 }, // Page undefined
  { surah: 28, ayah: 60 }, // Page undefined
  { surah: 28, ayah: 71 }, // Page undefined
  { surah: 28, ayah: 78 }, // Page undefined
  { surah: 28, ayah: 85 }, // Page undefined
  { surah: 29, ayah: 7 }, // Page undefined
  { surah: 29, ayah: 15 }, // Page undefined
  { surah: 29, ayah: 24 }, // Page undefined
  { surah: 29, ayah: 31 }, // Page undefined
  { surah: 29, ayah: 39 }, // Page undefined
  { surah: 29, ayah: 46 }, // Page undefined
  { surah: 29, ayah: 53 }, // Page undefined
  { surah: 29, ayah: 64 }, // Page undefined
  { surah: 30, ayah: 6 }, // Page undefined
  { surah: 30, ayah: 16 }, // Page undefined
  { surah: 30, ayah: 25 }, // Page undefined
  { surah: 30, ayah: 33 }, // Page undefined
  { surah: 30, ayah: 42 }, // Page undefined
  { surah: 30, ayah: 51 }, // Page undefined
  { surah: 31, ayah: 1 }, // Page undefined
  { surah: 31, ayah: 12 }, // Page undefined
  { surah: 31, ayah: 20 }, // Page undefined
  { surah: 31, ayah: 29 }, // Page undefined
  { surah: 32, ayah: 1 }, // Page undefined
  { surah: 32, ayah: 12 }, // Page undefined
  { surah: 32, ayah: 21 }, // Page undefined
  { surah: 33, ayah: 1 }, // Page undefined
  { surah: 33, ayah: 7 }, // Page undefined
  { surah: 33, ayah: 16 }, // Page undefined
  { surah: 33, ayah: 23 }, // Page undefined
  { surah: 33, ayah: 31 }, // Page undefined
  { surah: 33, ayah: 36 }, // Page undefined
  { surah: 33, ayah: 44 }, // Page undefined
  { surah: 33, ayah: 51 }, // Page undefined
  { surah: 33, ayah: 55 }, // Page undefined
  { surah: 33, ayah: 63 }, // Page undefined
  { surah: 34, ayah: 1 }, // Page undefined
  { surah: 34, ayah: 8 }, // Page undefined
  { surah: 34, ayah: 15 }, // Page undefined
  { surah: 34, ayah: 23 }, // Page undefined
  { surah: 34, ayah: 32 }, // Page undefined
  { surah: 34, ayah: 40 }, // Page undefined
  { surah: 34, ayah: 49 }, // Page undefined
  { surah: 35, ayah: 4 }, // Page undefined
  { surah: 35, ayah: 12 }, // Page undefined
  { surah: 35, ayah: 19 }, // Page undefined
  { surah: 35, ayah: 31 }, // Page undefined
  { surah: 35, ayah: 39 }, // Page undefined
  { surah: 35, ayah: 45 }, // Page undefined
  { surah: 36, ayah: 13 }, // Page undefined
  { surah: 36, ayah: 28 }, // Page undefined
  { surah: 36, ayah: 41 }, // Page undefined
  { surah: 36, ayah: 55 }, // Page undefined
  { surah: 36, ayah: 71 }, // Page undefined
  { surah: 37, ayah: 1 }, // Page undefined
  { surah: 37, ayah: 25 }, // Page undefined
  { surah: 37, ayah: 52 }, // Page undefined
  { surah: 37, ayah: 77 }, // Page undefined
  { surah: 37, ayah: 103 }, // Page undefined
  { surah: 37, ayah: 127 }, // Page undefined
  { surah: 37, ayah: 154 }, // Page undefined
  { surah: 38, ayah: 1 }, // Page undefined
  { surah: 38, ayah: 17 }, // Page undefined
  { surah: 38, ayah: 27 }, // Page undefined
  { surah: 38, ayah: 43 }, // Page undefined
  { surah: 38, ayah: 62 }, // Page undefined
  { surah: 38, ayah: 84 }, // Page undefined
  { surah: 39, ayah: 6 }, // Page undefined
  { surah: 39, ayah: 11 }, // Page undefined
  { surah: 39, ayah: 22 }, // Page undefined
  { surah: 39, ayah: 32 }, // Page undefined
  { surah: 39, ayah: 41 }, // Page undefined
  { surah: 39, ayah: 48 }, // Page undefined
  { surah: 39, ayah: 57 }, // Page undefined
  { surah: 39, ayah: 68 }, // Page undefined
  { surah: 39, ayah: 75 }, // Page undefined
  { surah: 40, ayah: 8 }, // Page undefined
  { surah: 40, ayah: 17 }, // Page undefined
  { surah: 40, ayah: 26 }, // Page undefined
  { surah: 40, ayah: 34 }, // Page undefined
  { surah: 40, ayah: 41 }, // Page undefined
  { surah: 40, ayah: 50 }, // Page undefined
  { surah: 40, ayah: 59 }, // Page undefined
  { surah: 40, ayah: 67 }, // Page undefined
  { surah: 40, ayah: 78 }, // Page undefined
  { surah: 41, ayah: 1 }, // Page undefined
  { surah: 41, ayah: 12 }, // Page undefined
  { surah: 41, ayah: 21 }, // Page undefined
  { surah: 41, ayah: 30 }, // Page undefined
  { surah: 41, ayah: 39 }, // Page undefined
  { surah: 41, ayah: 47 }, // Page undefined
  { surah: 42, ayah: 1 }, // Page undefined
  { surah: 42, ayah: 11 }, // Page undefined
  { surah: 42, ayah: 16 }, // Page undefined
  { surah: 42, ayah: 23 }, // Page undefined
  { surah: 42, ayah: 32 }, // Page undefined
  { surah: 42, ayah: 45 }, // Page undefined
  { surah: 42, ayah: 52 }, // Page undefined
  { surah: 43, ayah: 11 }, // Page undefined
  { surah: 43, ayah: 23 }, // Page undefined
  { surah: 43, ayah: 34 }, // Page undefined
  { surah: 43, ayah: 48 }, // Page undefined
  { surah: 43, ayah: 61 }, // Page undefined
  { surah: 43, ayah: 74 }, // Page undefined
  { surah: 44, ayah: 1 }, // Page undefined
  { surah: 44, ayah: 19 }, // Page undefined
  { surah: 44, ayah: 40 }, // Page undefined
  { surah: 45, ayah: 1 }, // Page undefined
  { surah: 45, ayah: 14 }, // Page undefined
  { surah: 45, ayah: 23 }, // Page undefined
  { surah: 45, ayah: 33 }, // Page undefined
  { surah: 46, ayah: 6 }, // Page undefined
  { surah: 46, ayah: 15 }, // Page undefined
  { surah: 46, ayah: 21 }, // Page undefined
  { surah: 46, ayah: 29 }, // Page undefined
  { surah: 47, ayah: 1 }, // Page undefined
  { surah: 47, ayah: 12 }, // Page undefined
  { surah: 47, ayah: 20 }, // Page undefined
  { surah: 47, ayah: 30 }, // Page undefined
  { surah: 48, ayah: 1 }, // Page undefined
  { surah: 48, ayah: 10 }, // Page undefined
  { surah: 48, ayah: 16 }, // Page undefined
  { surah: 48, ayah: 24 }, // Page undefined
  { surah: 48, ayah: 29 }, // Page undefined
  { surah: 49, ayah: 5 }, // Page undefined
  { surah: 49, ayah: 12 }, // Page undefined
  { surah: 50, ayah: 1 }, // Page undefined
  { surah: 50, ayah: 16 }, // Page undefined
  { surah: 50, ayah: 36 }, // Page undefined
  { surah: 51, ayah: 7 }, // Page undefined
  { surah: 51, ayah: 31 }, // Page undefined
  { surah: 51, ayah: 52 }, // Page undefined
  { surah: 52, ayah: 15 }, // Page undefined
  { surah: 52, ayah: 32 }, // Page undefined
  { surah: 53, ayah: 1 }, // Page undefined
  { surah: 53, ayah: 27 }, // Page undefined
  { surah: 53, ayah: 45 }, // Page undefined
  { surah: 54, ayah: 7 }, // Page undefined
  { surah: 54, ayah: 28 }, // Page undefined
  { surah: 54, ayah: 50 }, // Page undefined
  { surah: 55, ayah: 17 }, // Page undefined
  { surah: 55, ayah: 41 }, // Page undefined
  { surah: 55, ayah: 68 }, // Page undefined
  { surah: 56, ayah: 17 }, // Page undefined
  { surah: 56, ayah: 51 }, // Page undefined
  { surah: 56, ayah: 77 }, // Page undefined
  { surah: 57, ayah: 4 }, // Page undefined
  { surah: 57, ayah: 12 }, // Page undefined
  { surah: 57, ayah: 19 }, // Page undefined
  { surah: 57, ayah: 25 }, // Page undefined
  { surah: 58, ayah: 1 }, // Page undefined
  { surah: 58, ayah: 7 }, // Page undefined
  { surah: 58, ayah: 12 }, // Page undefined
  { surah: 58, ayah: 22 }, // Page undefined
  { surah: 59, ayah: 4 }, // Page undefined
  { surah: 59, ayah: 10 }, // Page undefined
  { surah: 59, ayah: 17 }, // Page undefined
  { surah: 60, ayah: 1 }, // Page undefined
  { surah: 60, ayah: 6 }, // Page undefined
  { surah: 60, ayah: 12 }, // Page undefined
  { surah: 61, ayah: 6 }, // Page undefined
  { surah: 62, ayah: 1 }, // Page undefined
  { surah: 62, ayah: 9 }, // Page undefined
  { surah: 63, ayah: 5 }, // Page undefined
  { surah: 64, ayah: 1 }, // Page undefined
  { surah: 64, ayah: 10 }, // Page undefined
  { surah: 65, ayah: 1 }, // Page undefined
  { surah: 65, ayah: 6 }, // Page undefined
  { surah: 66, ayah: 1 }, // Page undefined
  { surah: 66, ayah: 8 }, // Page undefined
  { surah: 67, ayah: 1 }, // Page undefined
  { surah: 67, ayah: 13 }, // Page undefined
  { surah: 67, ayah: 27 }, // Page undefined
  { surah: 68, ayah: 16 }, // Page undefined
  { surah: 68, ayah: 43 }, // Page undefined
  { surah: 69, ayah: 9 }, // Page undefined
  { surah: 69, ayah: 35 }, // Page undefined
  { surah: 70, ayah: 11 }, // Page undefined
  { surah: 70, ayah: 40 }, // Page undefined
  { surah: 71, ayah: 11 }, // Page undefined
  { surah: 72, ayah: 1 }, // Page undefined
  { surah: 72, ayah: 14 }, // Page undefined
  { surah: 73, ayah: 1 }, // Page undefined
  { surah: 73, ayah: 20 }, // Page undefined
  { surah: 74, ayah: 18 }, // Page undefined
  { surah: 74, ayah: 48 }, // Page undefined
  { surah: 75, ayah: 20 }, // Page undefined
  { surah: 76, ayah: 6 }, // Page undefined
  { surah: 76, ayah: 26 }, // Page undefined
  { surah: 77, ayah: 20 }, // Page undefined
  { surah: 78, ayah: 1 }, // Page undefined
  { surah: 78, ayah: 31 }, // Page undefined
  { surah: 79, ayah: 16 }, // Page undefined
  { surah: 80, ayah: 1 }, // Page undefined
  { surah: 81, ayah: 1 }, // Page undefined
  { surah: 82, ayah: 1 }, // Page undefined
  { surah: 83, ayah: 7 }, // Page undefined
  { surah: 83, ayah: 35 }, // Page undefined
  { surah: 85, ayah: 1 }, // Page undefined
  { surah: 86, ayah: 1 }, // Page undefined
  { surah: 87, ayah: 16 }, // Page undefined
  { surah: 89, ayah: 1 }, // Page undefined
  { surah: 89, ayah: 24 }, // Page undefined
  { surah: 91, ayah: 1 }, // Page undefined
  { surah: 92, ayah: 15 }, // Page undefined
  { surah: 95, ayah: 1 }, // Page undefined
  { surah: 97, ayah: 1 }, // Page undefined
  { surah: 98, ayah: 8 }, // Page undefined
  { surah: 100, ayah: 10 }, // Page undefined
  { surah: 103, ayah: 1 }, // Page undefined
  { surah: 106, ayah: 1 }, // Page undefined
  { surah: 109, ayah: 1 }, // Page undefined
  { surah: 112, ayah: 1 }, // Page undefined
];

export function getPageOfAyah(surah: number, ayah: number): number {
  for (let i = QURAN_PAGE_STARTS.length - 1; i >= 0; i--) {
    const p = QURAN_PAGE_STARTS[i];
    if (p.surah < surah || (p.surah === surah && p.ayah <= ayah)) {
      return i + 1; // 1-indexed
    }
  }
  return 1;
}

export function calculatePagesCount(fromSurah: number, fromAyah: number, toSurah: number, toAyah: number): number {
  const startPage = getPageOfAyah(fromSurah, fromAyah);
  const endPage = getPageOfAyah(toSurah, toAyah);
  return Math.max(1, endPage - startPage + 1);
}
